
import React, { useState } from 'react';
import type { ReportData, Recipient } from '../types';
import { BackIcon, CheckIcon, CopyIcon, RedoIcon, EmailIcon } from './icons';

interface ReportScreenProps {
  reportData: ReportData | null;
  recipients: Recipient[] | null;
  onBackToChat: () => void;
  onStartOver: () => void;
}

const ReportSection: React.FC<{ title: string; content: string | undefined }> = ({ title, content }) => (
  <div>
    <h3 className="text-sm font-semibold tracking-wider uppercase text-slate-400">{title}</h3>
    <p className="mt-1 text-base text-slate-300 whitespace-pre-wrap">{content || 'Not specified'}</p>
  </div>
);

const ReportScreen: React.FC<ReportScreenProps> = ({ reportData, recipients, onBackToChat, onStartOver }) => {
  const [copied, setCopied] = useState(false);

  if (!reportData || !recipients) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-4 text-center">
        <h2 className="text-2xl font-bold">Could not generate report.</h2>
        <p className="mt-2 text-slate-400">Something went wrong. Please go back and try again.</p>
        <button
          onClick={onBackToChat}
          className="flex items-center gap-2 px-4 py-2 mt-6 text-sm font-medium text-white transition-colors duration-200 bg-sky-600 rounded-md hover:bg-sky-700"
        >
          <BackIcon />
          <span>Back to Chat</span>
        </button>
      </div>
    );
  }

  const formatReportForCopy = () => {
    return `
INCIDENT REPORT
--------------------------------------
Date and Time of Incident:
${reportData.date}

Location of Incident:
${reportData.location}

Individuals Involved:
${reportData.involved}

Detailed Description of Events:
${reportData.description}

Impact:
${reportData.impact}
--------------------------------------
Generated by Safe Harbor AI
    `.trim();
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(formatReportForCopy());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareViaEmail = () => {
    const subject = "Incident Report Draft";
    const body = formatReportForCopy();
    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="max-w-4xl p-4 mx-auto my-8 bg-slate-900/50 backdrop-blur-sm md:p-8">
        <div className="p-8 bg-slate-800/50 border rounded-lg shadow-lg border-slate-700">
            <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
                <h2 className="text-2xl font-bold text-slate-100">Conversation Summary &amp; Report Draft</h2>
                <div className="flex gap-2">
                    <button
                        onClick={handleShareViaEmail}
                        className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white transition-colors duration-200 bg-gray-600 rounded-md hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400 focus:ring-offset-slate-800"
                    >
                        <EmailIcon />
                        <span>Email</span>
                    </button>
                    <button
                        onClick={handleCopyToClipboard}
                        className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white transition-colors duration-200 rounded-md bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:ring-offset-slate-800"
                    >
                        {copied ? <CheckIcon /> : <CopyIcon />}
                        <span>{copied ? 'Copied!' : 'Copy Text'}</span>
                    </button>
                </div>
            </div>
            <p className="mt-2 text-sm text-slate-400">
                This is a draft based on your conversation. Please review it carefully for accuracy and completeness before sharing it. You can copy the text and paste it into any editor to make changes.
            </p>
            <div className="mt-6 space-y-6 border-t border-slate-600 pt-6">
                <ReportSection title="Date and Time of Incident" content={reportData.date} />
                <ReportSection title="Location of Incident" content={reportData.location} />
                <ReportSection title="Individuals Involved" content={reportData.involved} />
                <ReportSection title="Detailed Description of Events" content={reportData.description} />
                <ReportSection title="Impact" content={reportData.impact} />
            </div>
        </div>

        <div className="p-8 mt-8 bg-slate-800/50 border rounded-lg shadow-lg border-slate-700">
            <h2 className="text-2xl font-bold text-slate-100">Suggested Recipients</h2>
            <p className="mt-2 text-sm text-slate-400">
                Depending on your situation, you might consider sharing this report with one of the following. This is not exhaustive and is not legal advice.
            </p>
            <ul className="mt-6 space-y-4">
                {recipients.map((recipient, index) => (
                    <li key={index} className="p-4 border rounded-md bg-slate-700/50 border-slate-700">
                        <h3 className="font-semibold text-sky-400">{recipient.name}</h3>
                        <p className="mt-1 text-sm text-slate-300">{recipient.description}</p>
                    </li>
                ))}
            </ul>
        </div>
        
        <div className="flex flex-col gap-4 mt-8 md:flex-row">
            <button onClick={onBackToChat} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 border rounded-md shadow-sm text-slate-200 bg-slate-700 border-slate-600 hover:bg-slate-600">
                <BackIcon />
                <span>Back to Chat</span>
            </button>
            <button onClick={onStartOver} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 bg-red-900/40 border border-red-800/60 rounded-md shadow-sm text-red-300 hover:bg-red-900/60">
                <RedoIcon />
                <span>Start New Session</span>
            </button>
        </div>
    </div>
  );
};

export default ReportScreen;