
import React, { useState } from 'react';
import type { ReportData, Recipient } from '../types';
import { BackIcon, CheckIcon, CopyIcon, RedoIcon, EmailIcon } from './icons';

interface ReportScreenProps {
  reportData: ReportData | null;
  recipients: Recipient[] | null;
  onBackToChat: () => void;
  onStartOver: () => void;
}

const ReportSection: React.FC<{ title: string; content: string | undefined }> = ({ title, content }) => (
  <div>
    <h3 className="text-sm font-semibold tracking-wider uppercase text-slate-400">{title}</h3>
    <p className="mt-1 text-base text-slate-300 whitespace-pre-wrap">{content || 'Not specified'}</p>
  </div>
);

const ReportScreen: React.FC<ReportScreenProps> = ({ reportData, recipients, onBackToChat, onStartOver }) => {
  const [copied, setCopied] = useState(false);

  // Helper: Only include fields that are filled
  const getFilledFields = () => {
    if (!reportData) return [];
    const fields = [
      { label: 'Date and Time of Incident', value: reportData.date },
      { label: 'Location of Incident', value: reportData.location },
      { label: 'Individuals Involved', value: reportData.involved },
      { label: 'Detailed Description of Events', value: reportData.description },
      { label: 'Impact', value: reportData.impact },
    ];
    return fields.filter(f => f.value && f.value.trim() && f.value !== 'Not specified');
  };

  // Helper: Generate summary
  const getSummary = () => {
    const filled = getFilledFields();
    if (filled.length === 0) return 'No incident details were provided.';
    return filled.map(f => `${f.label}: ${f.value}`).join('\n');
  };

  // Helper: Format email draft
  const formatReportForCopy = () => {
    const filled = getFilledFields();
    let draft = 'INCIDENT REPORT\n--------------------------------------\n';
    filled.forEach(f => {
      draft += `${f.label}:\n${f.value}\n\n`;
    });
    draft += '--------------------------------------\nGenerated by Afterhour Resources';
    return draft.trim();
  };

  if (!reportData || !recipients) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-4 text-center">
        <h2 className="text-2xl font-bold">Could not generate report.</h2>
        <p className="mt-2 text-slate-400">Something went wrong. Please go back and try again.</p>
        <button
          onClick={onBackToChat}
          className="flex items-center gap-2 px-4 py-2 mt-6 text-sm font-medium text-white transition-colors duration-200 bg-sky-600 rounded-md hover:bg-sky-700"
        >
          <BackIcon />
          <span>Back to Chat</span>
        </button>
      </div>
    );

  }
  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(formatReportForCopy());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };


  // For individual recipient
  const handleRecipientEmail = (recipient: Recipient) => {
    const subject = "Incident Report Draft";
    const body = formatReportForCopy();
    // If recipient has an email, use it; else, just open mailto
    const mailtoLink = `mailto:${encodeURIComponent((recipient as any).email || '')}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="max-w-4xl p-4 mx-auto my-8 bg-slate-900/50 backdrop-blur-sm md:p-8">
        <div className="p-8 bg-slate-800/50 border rounded-lg shadow-lg border-slate-700">
      <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
        <h2 className="text-2xl font-bold text-slate-100">Conversation Summary &amp; Report Draft</h2>
        <div className="flex gap-2">
          <button
            onClick={handleCopyToClipboard}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white transition-colors duration-200 rounded-md bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:ring-offset-slate-800"
          >
            {copied ? <CheckIcon /> : <CopyIcon />}
            <span>{copied ? 'Copied!' : 'Copy Text'}</span>
          </button>
        </div>
      </div>
            <p className="mt-2 text-sm text-slate-400">
                This is a draft based on your conversation. Only mentioned information is included. Please review for accuracy before sharing.
            </p>
            <div className="mt-6 space-y-6 border-t border-slate-600 pt-6">
                {/* Summary */}
                <div className="mb-4">
                  <h3 className="text-lg font-semibold text-slate-200">Summary</h3>
                  <pre className="mt-2 text-base text-slate-300 whitespace-pre-wrap">{getSummary()}</pre>
                </div>
                {/* Only show filled fields */}
                {getFilledFields().map((f, idx) => (
                  <ReportSection key={idx} title={f.label} content={f.value} />
                ))}
            </div>
        </div>

    <div className="p-8 mt-8 bg-slate-800/50 border rounded-lg shadow-lg border-slate-700">
      <h2 className="text-2xl font-bold text-slate-100">Suggested Recipients</h2>
      <p className="mt-2 text-sm text-slate-400">
        Depending on your situation, you might consider sharing this report with one of the following. This is not exhaustive and is not legal advice.
      </p>
      <ul className="mt-6 space-y-4">
        {recipients.map((recipient, index) => (
          <li key={index} className="p-4 border rounded-md bg-slate-700/50 border-slate-700 flex flex-col md:flex-row md:items-center md:justify-between">
            <div>
              <h3 className="font-semibold text-sky-400">{recipient.name}</h3>
              <p className="mt-1 text-sm text-slate-300">{recipient.description}</p>
            </div>
            <button
              className="mt-2 md:mt-0 flex items-center gap-2 px-3 py-2 text-sm font-medium text-white bg-sky-700 rounded-md hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:ring-offset-slate-800"
              onClick={() => handleRecipientEmail(recipient)}
            >
              <EmailIcon />
              <span>Email {recipient.name}</span>
            </button>
          </li>
        ))}
      </ul>
    </div>
        
        <div className="flex flex-col gap-4 mt-8 md:flex-row">
            <button onClick={onBackToChat} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 border rounded-md shadow-sm text-slate-200 bg-slate-700 border-slate-600 hover:bg-slate-600">
                <BackIcon />
                <span>Back to Chat</span>
            </button>
            <button onClick={onStartOver} className="flex items-center justify-center w-full gap-2 px-4 py-3 font-medium text-center transition-colors duration-200 bg-red-900/40 border border-red-800/60 rounded-md shadow-sm text-red-300 hover:bg-red-900/60">
                <RedoIcon />
                <span>Start New Session</span>
            </button>
        </div>
    </div>
  );
}
export default ReportScreen;